### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by JohnUrban** [comprna/humming#1]
If I used this tool and wanted to cite it, how would you prefer?
- This github link?
- A specific publication?
- The publication you cited? 
```
Humming code is based on the algorithms used in this publication

Eyras E, Caccamo M, Curwen V, Clamp M. ESTGenes: alternative splicing from ESTs in Ensembl. Genome Res. 2004 May;14(5):976-87. PMID: 15123595;
```

Thanks.

**Comment by JohnUrban** [comment]
I specifically used the `convert.pl` script to convert PAF to GFF.

**Comment by EduEyras** [comment]
Thanks John,

that's very nice of you

If possible, please cite the manuscript (Eyras et al. Genome Research 2004)
and kindly include the github link
https://github.com/comprna/humming in your methods section (or a similar
appropriate section)

Thanks a lot

Eduardo

**Comment by JohnUrban** [comment]
Will do. Thanks for getting back to me.
